import { Inter } from "next/font/google";
import Head from "next/head";

import { Album } from "@/types/Album";

const inter = Inter({ subsets: ["latin"] });

enum AlbumFavoriteStatus {
  NONE = "none",
  ALMOST = "almost",
  ALL = "all",
}

type AlbumDisplay = {
  id: string;
  title: Album["title"];
  artist: string;
  favoriteStatus: AlbumFavoriteStatus;
  illustration: Album["illustration"];
};
type AlbumsDisplay = Array<AlbumDisplay>;

export default function AlbumsDisplay() {
  const goToAlbumDetails = () => {};
  return (
    <>
      <Head>
        <title>Hoppr</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main></main>
    </>
  );
}
