#!/bin/sh
echo 'Fixing code style before committing 🏗️👷'
echo "Shouldn't be too long… ⚡"

npm run lint

npx lint-staged ||
(
    echo 'Something went wrong 🔨❌' 
    echo 'Check linter, add changes and try commit again'
    false;
)

npm run tscheck ||
(
    echo 'Something went wrong 🔨❌' 
    echo 'Check Typescript errors'
    false;
)